version: '3'

services:
  nextjs:
    container_name: fundsecure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    command: "npm run start"
